package com.campus.share.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_id
     *
     * @mbggenerated
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_type
     *
     * @mbggenerated
     */
    private String configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_key
     *
     * @mbggenerated
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_value
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_id
     *
     * @return the value of config.config_id
     *
     * @mbggenerated
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_id
     *
     * @param configId the value for config.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_type
     *
     * @return the value of config.config_type
     *
     * @mbggenerated
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_type
     *
     * @param configType the value for config.config_type
     *
     * @mbggenerated
     */
    public void setConfigType(String configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_key
     *
     * @return the value of config.config_key
     *
     * @mbggenerated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_key
     *
     * @param configKey the value for config.config_key
     *
     * @mbggenerated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_value
     *
     * @return the value of config.config_value
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_value
     *
     * @param configValue the value for config.config_value
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.rank
     *
     * @return the value of config.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.rank
     *
     * @param rank the value for config.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.remark
     *
     * @return the value of config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.remark
     *
     * @param remark the value for config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}