package com.campus.share.model;

import java.util.Date;

public class Reward {

    //自定义

    private String rewardTypeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.essay_id
     *
     * @mbggenerated
     */
    private Long essayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.reward_type_key
     *
     * @mbggenerated
     */
    private String rewardTypeKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.reward_detail
     *
     * @mbggenerated
     */
    private String rewardDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.max_receive_num
     *
     * @mbggenerated
     */
    private Integer maxReceiveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.id
     *
     * @return the value of reward.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.id
     *
     * @param id the value for reward.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.essay_id
     *
     * @return the value of reward.essay_id
     *
     * @mbggenerated
     */
    public Long getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.essay_id
     *
     * @param essayId the value for reward.essay_id
     *
     * @mbggenerated
     */
    public void setEssayId(Long essayId) {
        this.essayId = essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.reward_type_key
     *
     * @return the value of reward.reward_type_key
     *
     * @mbggenerated
     */
    public String getRewardTypeKey() {
        return rewardTypeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.reward_type_key
     *
     * @param rewardTypeKey the value for reward.reward_type_key
     *
     * @mbggenerated
     */
    public void setRewardTypeKey(String rewardTypeKey) {
        this.rewardTypeKey = rewardTypeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.update_time
     *
     * @return the value of reward.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.update_time
     *
     * @param updateTime the value for reward.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.reward_detail
     *
     * @return the value of reward.reward_detail
     *
     * @mbggenerated
     */
    public String getRewardDetail() {
        return rewardDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.reward_detail
     *
     * @param rewardDetail the value for reward.reward_detail
     *
     * @mbggenerated
     */
    public void setRewardDetail(String rewardDetail) {
        this.rewardDetail = rewardDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.max_receive_num
     *
     * @return the value of reward.max_receive_num
     *
     * @mbggenerated
     */
    public Integer getMaxReceiveNum() {
        return maxReceiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.max_receive_num
     *
     * @param maxReceiveNum the value for reward.max_receive_num
     *
     * @mbggenerated
     */
    public void setMaxReceiveNum(Integer maxReceiveNum) {
        this.maxReceiveNum = maxReceiveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.phone_number
     *
     * @return the value of reward.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.phone_number
     *
     * @param phoneNumber the value for reward.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getRewardTypeValue() {
        return rewardTypeValue;
    }

    public void setRewardTypeValue(String rewardTypeValue) {
        this.rewardTypeValue = rewardTypeValue;
    }
}