package com.campus.share.dao;

import com.campus.share.model.Reward;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface RewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Delete({
            "delete from reward",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Insert({
            "insert into reward (id, essay_id, ",
            "reward_type_key, update_time, ",
            "reward_detail, max_receive_num, ",
            "phone_number)",
            "values (#{id,jdbcType=BIGINT}, #{essayId,jdbcType=BIGINT}, ",
            "#{rewardTypeKey,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
            "#{rewardDetail,jdbcType=VARCHAR}, #{maxReceiveNum,jdbcType=INTEGER}, ",
            "#{phoneNumber,jdbcType=VARCHAR})"
    })
    int insert(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, essay_id, reward_type_key, update_time, reward_detail, max_receive_num, ",
            "phone_number",
            "from reward",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="essay_id", property="essayId", jdbcType=JdbcType.BIGINT),
            @Result(column="reward_type_key", property="rewardTypeKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="reward_detail", property="rewardDetail", jdbcType=JdbcType.VARCHAR),
            @Result(column="max_receive_num", property="maxReceiveNum", jdbcType=JdbcType.INTEGER),
            @Result(column="phone_number", property="phoneNumber", jdbcType=JdbcType.VARCHAR)
    })
    Reward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, essay_id, reward_type_key, update_time, reward_detail, max_receive_num, ",
            "phone_number",
            "from reward"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="essay_id", property="essayId", jdbcType=JdbcType.BIGINT),
            @Result(column="reward_type_key", property="rewardTypeKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="reward_detail", property="rewardDetail", jdbcType=JdbcType.VARCHAR),
            @Result(column="max_receive_num", property="maxReceiveNum", jdbcType=JdbcType.INTEGER),
            @Result(column="phone_number", property="phoneNumber", jdbcType=JdbcType.VARCHAR)
    })
    List<Reward> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Update({
            "update reward",
            "set essay_id = #{essayId,jdbcType=BIGINT},",
            "reward_type_key = #{rewardTypeKey,jdbcType=VARCHAR},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP},",
            "reward_detail = #{rewardDetail,jdbcType=VARCHAR},",
            "max_receive_num = #{maxReceiveNum,jdbcType=INTEGER},",
            "phone_number = #{phoneNumber,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Reward record);



    @Select({
            "select",
            "id, essay_id, reward_type_key, update_time, reward_detail, max_receive_num, ",
            "phone_number",
            "from reward",
            "where essay_id = #{essayId,jdbcType=BIGINT}",
            "limit 1"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="essay_id", property="essayId", jdbcType=JdbcType.BIGINT),
            @Result(column="reward_type_key", property="rewardTypeKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="reward_detail", property="rewardDetail", jdbcType=JdbcType.VARCHAR),
            @Result(column="max_receive_num", property="maxReceiveNum", jdbcType=JdbcType.INTEGER),
            @Result(column="phone_number", property="phoneNumber", jdbcType=JdbcType.VARCHAR)
    })
    Reward selectByEssayId(Long essayId);
}